# Generated by ChatGPT
# Prompt:
'''
我有一个jsonl文件，现在想把它转换并导入为MYSQL数据库，方便查询。
请编写python代码，将这个文件转换为sql文件。
下面是jsonl文件中数据的格式：
{"id": 9749, "category": "open_qa", "instruction_zh": "CEO代表什么意思", "context_zh": "", "response": "Chief Executive Officer", "instruction": "What does CEO stand for", "context": ""}
要求：字段一一对应，id为主键，其中category是枚举单选，其他均为可变长字符串。
category包括这些：information_extraction、classification、brainstorming、closed_qa、open_qa、general_qa、summarization、creative_writing
'''

import json

def jsonl_to_sql(jsonl_file, sql_file):
    # 枚举类型的定义
    categories = [
        "information_extraction", "classification", "brainstorming",
        "closed_qa", "open_qa", "general_qa", "summarization", "creative_writing"
    ]

    # 创建表的 SQL 语句
    create_table_sql = f"""
    CREATE TABLE data (
        id INT PRIMARY KEY,
        category ENUM({", ".join(f"'{cat}'" for cat in categories)}),
        instruction_zh TEXT,
        context_zh TEXT,
        response TEXT,
        instruction TEXT,
        context TEXT
    );
    """

    # 读取 JSONL 文件并生成 INSERT 语句
    insert_statements = []
    with open(jsonl_file, 'r', encoding='utf-8') as f:
        for line in f:
            record = json.loads(line.strip())
            insert_sql = f"""
            INSERT INTO data (id, category, instruction_zh, context_zh, response, instruction, context)
            VALUES (
                {record['id']},
                '{record['category']}',
                '{record['instruction_zh'].replace("'", "''")}',
                '{record['context_zh'].replace("'", "''")}',
                '{record['response'].replace("'", "''")}',
                '{record['instruction'].replace("'", "''")}',
                '{record['context'].replace("'", "''")}'
            );
            """
            insert_statements.append(insert_sql)

    # 写入到 SQL 文件
    with open(sql_file, 'w', encoding='utf-8') as f:
        f.write(create_table_sql + "\n")
        f.write("\n".join(insert_statements))
    print(f"SQL file has been generated: {sql_file}")

# 使用示例
jsonl_to_sql('chinese_dolly.jsonl', 'chinese_dolly.sql')
# 18M 的文件，不到1s就运行完了。
